version: '3.8'
services:
  nest-movie:
    image: ktphuc1994/movie-nestjs
    ports:
      - 8080:8080
    depends_on:
      - mysql_movie
    env_file:
      - .env
    networks:
      - node-network
  mysql_movie:
    image: mysql
    container_name: mysql_movie
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - mysql_movie:/var/lib/mysql
    networks:
      - node-network
volumes:
  mysql_movie:
    driver: local
    name: node25-nest-movie
networks:
  node-network: